name: 'Maximize build disk space (Only remove unwanted software)'
description: 'Maximize the available disk space for your build job by removing unwanted software'
branding:
  icon: 'crop'
  color: 'blue'
inputs:
  use-sudo:
    description: 'Whether to use sudo for removing files. Default is true.'
    required: false
    default: 'true'
  remove-dotnet:
    description: 'Removes .NET runtime and libraries. (frees ~2 GB)'
    required: false
    default: 'true'
  remove-android:
    description: 'Removes Android SDKs and Tools. (frees ~9 GB)'
    required: false
    default: 'true'
  remove-haskell:
    description: 'Removes GHC (Haskell) artifacts. (frees ~5.2 GB)'
    required: false
    default: 'false'
  remove-codeql:
    description: 'Removes CodeQL Action Bundles. (frees ~5.4 GB)'
    required: false
    default: 'false'
  remove-docker-images:
    description: 'Removes cached Docker images. (frees ~3.2 GB)'
    required: false
    default: 'false'
  remove-large-packages:
    description: 'Removes unwanted large Apt packages. (frees ~3.1 GB)'
    required: false
    default: 'false'
  remove-cached-tools:
    description: 'Removes cached tools used by setup actions by GitHub. (frees ~8.3 GB)'
    required: false
    default: 'false'
  remove-swapfile:
    description: 'Removes the Swapfile. (frees ~4 GB)'
    required: false
    default: 'false'
  verbose:
    description: 'Enables detailed logging of the action'
    required: false
    default: 'true'
  remove-large-packages:
    description: 'Removes large packages. (frees ~5 GB)'
    required: false
    default: 'true'
  remove-docker-cached-images:
    description: 'Removes cached images in docker. (frees ~5 GB)'
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: Disk space report before modification
      shell: bash
      run: |
          echo "==> Available space before cleanup"
          echo
          df -h

    - name: Maximize build disk space
      shell: bash
      run: |
          set -euo pipefail
          if [[ "${{ inputs.use-sudo }}" == 'true' ]]; then
            SUDO_PREFIX="sudo"
          else
            SUDO_PREFIX=""
          fi

          echo -n "  Removing:     "
          if [[ ${{ inputs.remove-dotnet }} == 'true' ]]; then
            echo -n "dotnet "
          fi
          if [[ ${{ inputs.remove-android }} == 'true' ]]; then
            echo -n "android "
          fi
          if [[ ${{ inputs.remove-haskell }} == 'true' ]]; then
            echo -n "haskell "
          fi
          if [[ ${{ inputs.remove-codeql }} == 'true' ]]; then
            echo -n "codeql "
          fi
          if [[ ${{ inputs.remove-docker-images }} == 'true' ]]; then
            echo -n "docker "
          fi
          if [[ ${{ inputs.remove-large-packages }} == 'true' ]]; then
            echo -n "large_packages "
          fi
          if [[ ${{ inputs.remove-cached-tools }} == 'true' ]]; then
            echo -n "cached_tools "
          fi
          if [[ ${{ inputs.remove-swapfile }} == 'true' ]]; then
            echo -n "swapfile "
          fi
          if [[ ${{ inputs.remove-docker-cached-images }} == 'true' ]]; then
            echo -n "remove-docker-cached-images "
          fi
          if [[ ${{ inputs.remove-codeql }} == 'true' ]]; then
            echo -n "codeql "
          fi
          echo

          verbose=""
          if [[ ${{ inputs.verbose }} == 'true' ]]; then
            verbose=-v
          fi
  
          echo "Removing unwanted software... "
          if [[ ${{ inputs.remove-dotnet }} == 'true' ]]; then
            $SUDO_PREFIX rm -rf ${verbose} /usr/share/dotnet
          fi
          if [[ ${{ inputs.remove-android }} == 'true' ]]; then
            $SUDO_PREFIX rm -rf ${verbose} /usr/local/lib/android
          fi
          if [[ ${{ inputs.remove-haskell }} == 'true' ]]; then
            $SUDO_PREFIX rm -rf ${verbose} /opt/ghc
            $SUDO_PREFIX rm -rf ${verbose} /usr/local/.ghcup
          fi
          if [[ ${{ inputs.remove-codeql }} == 'true' ]]; then
            $SUDO_PREFIX rm -rf ${verbose} /opt/hostedtoolcache/CodeQL
          fi
          if [[ ${{ inputs.remove-docker-images }} == 'true' ]]; then
            if [[ ${{ inputs.verbose }} == 'true' ]]; then
              $SUDO_PREFIX docker image prune --all --force
            else
              $SUDO_PREFIX docker image prune --all --force > /dev/null
            fi  
          fi
          CODENAME=$(lsb_release -c | cut -d ":" -f 2 | xargs)
          if [[ (${CODENAME} = focal) || (${CODENAME} = jammy) ]]; then
            POWERSHELL=powershell
          else
            POWERSHELL=powershell-lts
          fi
          if [[ ${{ inputs.remove-large-packages }} == 'true' ]]; then
            if [[ ${{ inputs.verbose }} == 'true' ]]; then
              $SUDO_PREFIX apt-get remove -y '^aspnetcore-.*'
              $SUDO_PREFIX apt-get remove -y '^dotnet-.*'
              $SUDO_PREFIX apt-get remove -y '^llvm-.*'
              $SUDO_PREFIX apt-get remove -y 'php.*'
              $SUDO_PREFIX apt-get remove -y '^mongodb-.*'
              $SUDO_PREFIX apt-get remove -y '^mysql-.*'
              $SUDO_PREFIX apt-get remove -y azure-cli google-chrome-stable firefox ${POWERSHELL} mono-devel libgl1-mesa-dri --fix-missing
              if [[ (${CODENAME} = focal) || (${CODENAME} = jammy) ]]; then
                $SUDO_PREFIX apt-get remove -y google-cloud-sdk --fix-missing
                $SUDO_PREFIX apt-get remove -y google-cloud-cli --fix-missing
              fi
              $SUDO_PREFIX apt-get autoremove -y
              $SUDO_PREFIX apt-get clean
            else
              $SUDO_PREFIX apt-get remove -y '^aspnetcore-.*' > /dev/null
              $SUDO_PREFIX apt-get remove -y '^dotnet-.*' > /dev/null
              $SUDO_PREFIX apt-get remove -y '^llvm-.*' > /dev/null
              $SUDO_PREFIX apt-get remove -y 'php.*' > /dev/null
              $SUDO_PREFIX apt-get remove -y '^mongodb-.*' > /dev/null
              $SUDO_PREFIX apt-get remove -y '^mysql-.*' > /dev/null
              $SUDO_PREFIX apt-get remove -y azure-cli google-chrome-stable firefox ${POWERSHELL} mono-devel libgl1-mesa-dri --fix-missing > /dev/null
              
              if [[ (${CODENAME} = focal) || (${CODENAME} = jammy) ]]; then
                $SUDO_PREFIX apt-get remove -y google-cloud-sdk --fix-missing > /dev/null
                $SUDO_PREFIX apt-get remove -y google-cloud-cli --fix-missing > /dev/null
              fi
              $SUDO_PREFIX apt-get autoremove -y > /dev/null
              $SUDO_PREFIX apt-get clean > /dev/null
            fi 
          fi
          if [[ ${{ inputs.remove-cached-tools }} == 'true' ]]; then
            $SUDO_PREFIX rm -rf ${verbose} "$AGENT_TOOLSDIRECTORY"
          fi
          if [[ ${{ inputs.remove-swapfile }} == 'true' ]]; then
            $SUDO_PREFIX swapoff -a ${verbose}
            $SUDO_PREFIX rm -f ${verbose} /mnt/swapfile
          fi
          if [[ ${{ inputs.remove-docker-cached-images }} == 'true' ]]; then
            $SUDO_PREFIX docker image prune --all --force
          fi
          echo "... done"

    - name: Disk space report after modification
      shell: bash
      run: |
          echo "==> Available space after cleanup"
          echo
          df -h
