name: 'Maximize build disk space (Only remove unwanted software)'
description: 'Maximize the available disk space for your build job by removing unwanted software'
branding:
  icon: 'crop'
  color: 'blue'
inputs:
  remove-dotnet:
    description: 'Removes .NET runtime and libraries. (frees ~4 GB)'
    required: false
    default: 'true'
  remove-android:
    description: 'Removes Android SDKs and Tools. (frees ~11 GB)'
    required: false
    default: 'true'
  remove-haskell:
    description: 'Removes GHC (Haskell) artifacts. (frees a few MBs)'
    required: false
    default: 'true'
  remove-large-packages:
    description: 'Removes large packages. (frees ~5 GB)'
    required: false
    default: 'true'
runs:
  using: "composite"
  steps:
    - name: Disk space report before modification
      shell: bash
      run: |
          echo "==> Available space before cleanup"
          echo
          df -h

    - name: Maximize build disk space
      shell: bash
      run: |
          set -euo pipefail

          echo -n "  Removing:     "
          if [[ ${{ inputs.remove-dotnet }} == 'true' ]]; then
            echo -n "dotnet "
          fi
          if [[ ${{ inputs.remove-android }} == 'true' ]]; then
            echo -n "android "
          fi
          if [[ ${{ inputs.remove-haskell }} == 'true' ]]; then
            echo -n "haskell "
          fi
          if [[ ${{ inputs.remove-large-packages }} == 'true' ]]; then
            echo -n "large-packages "
          fi
          echo

          echo "Removing unwanted software... "
          if [[ ${{ inputs.remove-dotnet }} == 'true' ]]; then
            sudo rm -rf /usr/share/dotnet
          fi
          if [[ ${{ inputs.remove-android }} == 'true' ]]; then
            sudo rm -rf /usr/local/lib/android
          fi
          if [[ ${{ inputs.remove-haskell }} == 'true' ]]; then
            sudo rm -rf /opt/ghc
          fi
          if [[ ${{ inputs.remove-large-packages }} == 'true' ]]; then
            sudo apt-get purge -y \
              '^llvm-.*' \
              'php.*' \
              '^mongodb-.*' \
              '^mysql-.*' \
              azure-cli \
              google-cloud-sdk \
              google-chrome-stable \
              firefox \
              powershell \
              microsoft-edge-stable \
              mono-devel
            sudo apt-get autoremove -y
            sudo apt-get clean
          fi
          echo "... done"

    - name: Disk space report after modification
      shell: bash
      run: |
          echo "==> Available space after cleanup"
          echo
          df -h
